# Lista de fornecedores-alvo para consulta
TARGET_PRODUCTS = [
    "Palo Alto Networks",
    "Fortinet",
    "Check Point Software Technologies",
    "Cisco",
    "Sophos",
    "Juniper Networks",
    "Barracuda Networks",
    "Forcepoint",
    "Huawei",
    "SonicWall",
    "WatchGuard",
    "Versa Networks",
    "Cato Networks",
    "Trend Micro",
    "Hillstone Networks",
    "Stormshield",
    "F5 Networks",
    "Zscaler",
    "McAfee",
    "Blockbit",
    "Meraki",
    "Aruba",
    "MikroTik"
    "Dell",
    "ZTE ",
    "Ubiquiti ",
    "Ruckus",
    "TP-Link",
    "D-Link",
    "Netgear",
    "Broadcom",
    "ADTRAN",
    "Ciena Corporation",
    "Ericsson",
    "Nokia",
    "Microsoft",
    "Apple",
    "Linux",
    "Amazon",
    "Tellabs",
    "Oracle",
    "IBM",
    "Google",
    "Extreme Networks",
    "DZS Inc",
    "Chima",
    "Calix",
    "Samsung",
    "SAP",
    "Intelbras"
    "Siemens",
    "ABB",
    "Schneider Electric",
    "Rockwell Automation",
    "Emerson Electric",
    "Mitsubishi Electric",
    "Bosch",
    "National Instruments",
    "Intel",
    "Amd",
    "Nvidia"
]